### ISSUE TITLE
Task Scheduler Middleware Error

### ISSUE THREAD

**Issue by scott-weeden** [smartstore/Smartstore#1118]
**Describe the bug**
This is a new setup, I selected SQLlite, Mac OSX x86, nginx reverse proxy

Set the url for the task scheduler middleware in 
  usersettings.json

If I set the task scheduler to a much higher number the error doesn't occur (until a much later time). The error crashes the app I can't keep the website running :(

Any Suggestions?

Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Smartstore.Scheduling.DefaultTaskScheduler.HandleException(Exception exception, Uri uri, Boolean& isTimeout) in D:\Git\Smartstore.Full\Smartstore\src\Smartstore\Scheduling\Services\DefaultTaskScheduler.cs:line 272
   at Smartstore.Scheduling.DefaultTaskScheduler.CallEndpointAsync(String action, Boolean isPoll) in D:\Git\Smartstore.Full\Smartstore\src\Smartstore\Scheduling\Services\DefaultTaskScheduler.cs:line 207
   at Smartstore.Scheduling.DefaultTaskScheduler.OnTimerTick(Object state) in D:\Git\Smartstore.Full\Smartstore\src\Smartstore\Scheduling\Services\DefaultTaskScheduler.cs:line 165
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by mgesing** [comment]
This should have been fixed by 30608cf.
