### ISSUE TITLE
DB error when adding product to the cart

### ISSUE THREAD

**Issue by nagulka** [smartstore/Smartstore#1133]
**Describe the bug**
![image](https://github.com/smartstore/Smartstore/assets/37404910/b740c2a1-2300-438b-b393-5a04e316c92a)
2024-07-01 17:57:43.134 CEST [7980] FEHLER:  NULL-Wert in Spalte Â»ActiveÂ« von Relation Â»ShoppingCartItemÂ« verletzt Not-Null-Constraint
2024-07-01 17:57:43.134 CEST [7980] DETAIL:  Fehlgeschlagene Zeile enthÃ¤lt (9, null, 1, null, null, 82, 1, null, 0.0000, 1, 1, 2024-07-01 15:57:43.064106, 2024-07-01 15:57:43.064106).
2024-07-01 17:57:43.134 CEST [7980] ANWEISUNG:  INSERT INTO "ShoppingCartItem" ("BundleItemId", "CreatedOnUtc", "CustomerEnteredPrice", "CustomerId", "ParentItemId", "ProductId", "Quantity", "AttributesXml", "ShoppingCartTypeId", "StoreId", "UpdatedOnUtc")

	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)

	RETURNING "Id"

**To Reproduce**
DB: PostgreSQL, new database with 1 product and 1 user (admin). 
Add the product to the cart. No reaction, no messages. You can see the 500 error in web debugger and sql error in db log. The log entry in the Log table from smartstore database:
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Npgsql.PostgresException (0x80004005): 23502: NULL-Wert in Spalte »Active« von Relation »ShoppingCartItem« verletzt Not-Null-Constraint

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
  Exception data:
    Severity: FEHLER
    SqlState: 23502
    MessageText: NULL-Wert in Spalte »Active« von Relation »ShoppingCartItem« verletzt Not-Null-Constraint
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: public
    TableName: ShoppingCartItem
    ColumnName: Active
    File: execMain.c
    Line: 2009
    Routine: ExecConstraints
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Smartstore.Data.DbSaveChangesOperation.ExecuteInternal(Boolean acceptAllChangesOnSuccess, Boolean async, CancellationToken cancelToken) in E:\entwicklung-smartstore\Smartstore\src\Smartstore\Data\DbSaveChangesOperation.cs:line 75
   at Smartstore.Data.DbSaveChangesOperation.ExecuteInternal(Boolean acceptAllChangesOnSuccess, Boolean async, CancellationToken cancelToken) in E:\entwicklung-smartstore\Smartstore\src\Smartstore\Data\DbSaveChangesOperation.cs:line 85
   at Smartstore.Data.HookingDbContext.SaveChangesInternal(Boolean acceptAllChangesOnSuccess, Boolean async, CancellationToken cancelToken) in E:\entwicklung-smartstore\Smartstore\src\Smartstore\Data\HookingDbContext.cs:line 263
   at Smartstore.Core.Checkout.Cart.ShoppingCartService.AddItemToCartAsync(AddToCartContext ctx) in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Core\Checkout\Cart\Services\ShoppingCartService.cs:line 78
   at Smartstore.Core.Checkout.Cart.ShoppingCartService.AddToCartAsync(AddToCartContext ctx) in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Core\Checkout\Cart\Services\ShoppingCartService.cs:line 255
   at Smartstore.Web.Controllers.ShoppingCartController.AddProduct(Int32 productId, Int32 shoppingCartTypeId, ProductVariantQuery query) in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Web\Controllers\ShoppingCartController.cs:line 595
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Smartstore.Core.Bootstrapping.CheckoutBootstrappingExtensions.<>c.<<UseCheckoutState>b__0_0>d.MoveNext() in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Core\Checkout\Bootstrapping\CheckoutBootstrappingExtensions.cs:line 22
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Smartstore.Web.Api.Startup.<>c.<<BuildPipeline>b__3_7>d.MoveNext() in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Modules\Smartstore.WebApi\Startup.cs:line 227
--- End of stack trace from previous location ---
   at Smartstore.ExceptionExtensions.ReThrow(Exception exception) in E:\entwicklung-smartstore\Smartstore\src\Smartstore\Extensions\ExceptionExtensions.cs:line 15
   at Smartstore.Web.Api.Startup.ProcessException(HttpContext context, Exception ex) in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Modules\Smartstore.WebApi\Startup.cs:line 258
   at Smartstore.Web.Api.Startup.<>c.<<BuildPipeline>b__3_7>d.MoveNext() in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Modules\Smartstore.WebApi\Startup.cs:line 231
--- End of stack trace from previous location ---
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 94
   at Smartstore.Core.Localization.RequestCultureMiddleware.Invoke(HttpContext context, IWorkContext workContext) in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Core\Platform\Localization\Services\RequestCultureMiddleware.cs:line 70
   at Smartstore.Core.Logging.RequestLoggingMiddleware.InvokeAsync(HttpContext httpContext, IWebHelper webHelper, IWorkContext workContext) in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Core\Platform\Logging\Serilog\RequestLoggingMiddleware.cs:line 57
   at Smartstore.Core.Bootstrapping.CommonBuilderExtensions.<>c.<<UseWorkContext>b__1_0>d.MoveNext() in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Core\Platform\Common\Bootstrapping\CommonBuilderExtensions.cs:line 35
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Smartstore.Core.Bootstrapping.LocalizationBuilderExtensions.OnAfterRouting(HttpContext context, Func`1 next) in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Core\Platform\Localization\Bootstrapping\LocalizationBuilderExtensions.cs:line 117
   at Smartstore.Core.Bootstrapping.LocalizationBuilderExtensions.OnBeforeRouting(HttpContext context, Func`1 next) in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Core\Platform\Localization\Bootstrapping\LocalizationBuilderExtensions.cs:line 81
   at Microsoft.AspNetCore.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.OData.Query.ODataQueryRequestMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.OData.Routing.ODataRouteDebugMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Smartstore.Core.Bootstrapping.CommonBuilderExtensions.<>c.<<UseSecurityHeaders>b__3_0>d.MoveNext() in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Core\Platform\Common\Bootstrapping\CommonBuilderExtensions.cs:line 60
--- End of stack trace from previous location ---
   at Smartstore.Core.Bootstrapping.CommonBuilderExtensions.<>c.<<UsePoweredBy>b__2_0>d.MoveNext() in E:\entwicklung-smartstore\Smartstore\src\Smartstore.Core\Platform\Common\Bootstrapping\CommonBuilderExtensions.cs:line 48
--- End of stack trace from previous location ---
   at Smartstore.Engine.Initialization.ApplicationInitializerMiddleware.Invoke(HttpContext context) in E:\entwicklung-smartstore\Smartstore\src\Smartstore\Engine\Initialization\ApplicationInitializerMiddleware.cs:line 77
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Expected behavior**
The product added to the car.

**Screenshots**
<img width="874" alt="image" src="https://github.com/smartstore/Smartstore/assets/37404910/754abdfb-28f4-47f1-97f2-5ffed267331e">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Chrome

**Additional context**

**Comment by mgesing** [comment]
I cannot reproduce this with the current branch `main`. In the SQL statement, the order of the column names seems to be different from the order of the values.
