### ISSUE TITLE
PayPal: `ArgumentNullException` possible in all request object constructors

### ISSUE THREAD

**Issue by mgesing** [smartstore/Smartstore#1151]
`IOException` is catched, `ArgumentNullException` is not. Example:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'stringToEscape')
   at System.ArgumentNullException.Throw(String paramName)
   at System.UriHelper.EscapeString(String stringToEscape, Boolean checkExistingEscaped, ReadOnlySpan`1 unreserved, Char forceEscape1, Char forceEscape2)
   at System.Uri.EscapeDataString(String stringToEscape)
   at Smartstore.PayPal.Client.Messages.CapturesRefundRequest..ctor(String captureId)
   at Smartstore.PayPal.Client.PayPalHttpClient.RefundPaymentAsync(RefundPaymentRequest request, RefundPaymentResult result, CancellationToken cancelToken)
   at Smartstore.PayPal.Providers.PayPalInvoiceProvider.RefundAsync(RefundPaymentRequest request)
   at Smartstore.Core.Checkout.Payment.PaymentService.RefundAsync(RefundPaymentRequest refundPaymentRequest)
   at Smartstore.Core.Checkout.Orders.OrderProcessingService.RefundAsync(Order order)
   at Smartstore.ExceptionExtensions.ReThrow(Exception exception)
   at Smartstore.Core.Checkout.Orders.OrderProcessingService.RefundAsync(Order order)
   at Smartstore.Admin.Controllers.OrderController.RefundOrder(Int32 id)
```

Occurred in POST /admin/order/edit/{ID}/

**Comment by Michael-Herzog** [comment]
Since the creation of this issue PayPal Request API was heavily refactored. 
I havn't seen this error in a long time.
And the corresponding code looks absolutly safe.
