### ISSUE TITLE
Internal Server Error when configuring the Page Builder

### ISSUE THREAD

**Issue by mohamedsakeel** [smartstore/Smartstore#1177]
**Internal Server Error**
I have setup the smartstore in my server and i downloaded the Page builder module from marketplace and I uploaded it and it got installed, then when I try to configure it, I am getting an Internal server error

```
Controller: Error, Action: Error, Status: 500 (InternalServerError)

Method not found: 'Void Smartstore.Web.TagHelpers.Shared.ZoneTagHelper.set_ZoneName(System.String)'.
```

Smartstore version is 5.1.0
![image](https://github.com/user-attachments/assets/2d641f98-482b-49a9-b233-9a63712e34b4)

The logged error

```
System.MissingMethodException: Method not found: 'Void Smartstore.Web.TagHelpers.Shared.ZoneTagHelper.set_ZoneName(System.String)'.
   at AspNetCoreGeneratedDocument.Views_StoryAdmin_List.ExecuteAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at AspNetCoreGeneratedDocument.Views_StoryAdmin_List.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Smartstore.Core.Bootstrapping.CheckoutBootstrappingExtensions.<>c.<<UseCheckoutState>b__0_0>d.MoveNext() in F:\E-Commerce Website\Smartstore\src\Smartstore.Core\Checkout\Bootstrapping\CheckoutBootstrappingExtensions.cs:line 22
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Smartstore.Web.Api.Startup.<>c.<<BuildPipeline>b__3_7>d.MoveNext()
--- End of stack trace from previous location ---
   at Smartstore.ExceptionExtensions.ReThrow(Exception exception) in F:\E-Commerce Website\Smartstore\src\Smartstore\Extensions\ExceptionExtensions.cs:line 15
   at Smartstore.Web.Api.Startup.ProcessException(HttpContext context, Exception ex)
   at Smartstore.Web.Api.Startup.<>c.<<BuildPipeline>b__3_7>d.MoveNext()
--- End of stack trace from previous location ---
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 112
   at Smartstore.Core.Localization.RequestCultureMiddleware.Invoke(HttpContext context, IWorkContext workContext) in F:\E-Commerce Website\Smartstore\src\Smartstore.Core\Platform\Localization\Services\RequestCultureMiddleware.cs:line 70
   at Smartstore.Core.Logging.RequestLoggingMiddleware.InvokeAsync(HttpContext httpContext, IWebHelper webHelper, IWorkContext workContext) in F:\E-Commerce Website\Smartstore\src\Smartstore.Core\Platform\Logging\Serilog\RequestLoggingMiddleware.cs:line 57
   at Smartstore.Core.Bootstrapping.CommonBuilderExtensions.<>c.<<UseWorkContext>b__1_0>d.MoveNext() in F:\E-Commerce Website\Smartstore\src\Smartstore.Core\Platform\Common\Bootstrapping\CommonBuilderExtensions.cs:line 35
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Smartstore.Core.Bootstrapping.LocalizationBuilderExtensions.OnAfterRouting(HttpContext context, Func1 next) in F:\E-Commerce Website\Smartstore\src\Smartstore.Core\Platform\Localization\Bootstrapping\LocalizationBuilderExtensions.cs:line 117
   at Smartstore.Core.Bootstrapping.LocalizationBuilderExtensions.OnBeforeRouting(HttpContext context, Func1 next) in F:\E-Commerce Website\Smartstore\src\Smartstore.Core\Platform\Localization\Bootstrapping\LocalizationBuilderExtensions.cs:line 81
   at Microsoft.AspNetCore.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.OData.Query.ODataQueryRequestMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Smartstore.Core.Bootstrapping.CommonBuilderExtensions.<>c.<<UseSecurityHeaders>b__3_0>d.MoveNext() in F:\E-Commerce Website\Smartstore\src\Smartstore.Core\Platform\Common\Bootstrapping\CommonBuilderExtensions.cs:line 60
--- End of stack trace from previous location ---
   at Smartstore.Core.Bootstrapping.CommonBuilderExtensions.<>c.<<UsePoweredBy>b__2_0>d.MoveNext() in F:\E-Commerce Website\Smartstore\src\Smartstore.Core\Platform\Common\Bootstrapping\CommonBuilderExtensions.cs:line 48
--- End of stack trace from previous location ---
   at Smartstore.Web.Bundling.BundleMiddleware.InvokeAsync(HttpContext httpContext) in F:\E-Commerce Website\Smartstore\src\Smartstore.Web.Common\Bundling\BundleMiddleware.cs:line 46
   at Smartstore.Engine.Initialization.ApplicationInitializerMiddleware.Invoke(HttpContext context) in F:\E-Commerce Website\Smartstore\src\Smartstore\Engine\Initialization\ApplicationInitializerMiddleware.cs:line 81
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Comment by mgesing** [comment]
You are not using Smartstore 5.1.0, but the current code of the main branch. This is used for current development work and should not be used live. The Page-Builder plugin is not compatible with the main branch, that's why you get this error. If you want to test the Page-Builder, you must use the official release 5.1.0.

**Comment by mohamedsakeel** [comment]
> You are not using Smartstore 5.1.0, but the current code of the main branch. This is used for current development work and should not be used live. The Page-Builder plugin is not compatible with the main branch, that's why you get this error. If you want to test the Page-Builder, you must use the official release 5.1.0.

@mgesing 
No, I am using the Smartstore 5.1.0 version I downloaded from the official website community edition
Not sure why this error occurred 

If you have any fix please let me know

**Comment by martgaiger** [comment]
> > You are not using Smartstore 5.1.0, but the current code of the main branch. This is used for current development work and should not be used live. The Page-Builder plugin is not compatible with the main branch, that's why you get this error. If you want to test the Page-Builder, you must use the official release 5.1.0.
> 
> @mgesing No, I am using the Smartstore 5.1.0 version I downloaded from the official website community edition Not sure why this error occurred
> 
> If you have any fix please let me know

Did you manage to solve this problem? I have the same problem
