### ISSUE TITLE
Can not load theme.css - unable to load libsass

### ISSUE THREAD

**Issue by FranktheFurter** [smartstore/Smartstore#542]
A Clean pull of the repo builds and starts, but the page fails to load/generate its .css files.

![image](https://user-images.githubusercontent.com/86846342/189061251-72f462c5-da77-42e6-8597-a26ef04e91b8.jpeg)

**Errormessage**
```
[09:18:17 ERR] Error while processing bundle '/themes/flex/theme.css'.
System.DllNotFoundException: Unable to load shared library 'libsass' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibsass, 0x0001): tried: 'liblibsass' (no such file), '/usr/local/lib/liblibsass' (no such file), '/usr/lib/liblibsass' (no such file), '/Users/marcfrankfurter/Repositorys/Smartstore/src/Smartstore.Web/liblibsass' (no such file)
   at SharpScss.LibSass.sass_make_data_context(String source_string)
   at SharpScss.Scss.FromCore(String fromStringOrFile, Boolean fromFile, ScssOptions options)
   at Smartstore.Web.Bundling.Processors.SassProcessor.ProcessAsync(BundleContext context) in /Users/marcfrankfurter/Repositorys/Smartstore/src/Smartstore.Web.Common/Bundling/Processors/SassProcessor.cs:line 32
   at Smartstore.Web.Bundling.Bundle.GenerateBundleResponseAsync(BundleContext context) in /Users/marcfrankfurter/Repositorys/Smartstore/src/Smartstore.Web.Common/Bundling/Bundle.cs:line 322
   at Smartstore.Web.Bundling.DefaultBundleBuilder.BuildBundleAsync(Bundle bundle, BundleCacheKey cacheKey, IDictionary`2 dataTokens, HttpContext httpContext, BundlingOptions options) in /Users/marcfrankfurter/Repositorys/Smartstore/src/Smartstore.Web.Common/Bundling/BundleBuilder.cs:line 94
   at Smartstore.Web.Bundling.BundleMiddleware.InvokeAsync(HttpContext httpContext) in /Users/marcfrankfurter/Repositorys/Smartstore/src/Smartstore.Web.Common/Bundling/BundleMiddleware.cs:line 82
```

**Desktop (please complete the following information):**
 - OS: [macOs 12.5.1 ARM ]
 - Browser [e.g. chrome]
 - Visual Studio Professional 2022 for Mac Version 17.3.1 (build 411)
 - NET SDK (Arm64) 6.0.4

**Comment by muratcakir** [comment]
Unfortunately, Smartstore development on macOS is not tested and not recommended.

**Comment by kurtulusmengukan** [comment]
Hi @FranktheFurter, @muratcakir, 
I can run it :)

You need to install libsass with brew; "brew install libsass"
next go to folder "/opt/homebrew/Cellar/libsass/3.6.5/lib" copy file "libsass.dylib" 
copy "/usr/local/lib" to this directory

<img width="277" alt="Screenshot 2022-11-26 at 16 26 46" src="https://user-images.githubusercontent.com/5060275/204091271-078b96a1-e9eb-4117-976f-77a0c60b5f06.png">
