### ISSUE TITLE
Sitemap folder missing after install

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#662]
**Describe the bug**
Seems Sitemap folder is not always created after install?

**To Reproduce**
Install, add a language and set it active/published.
Check the log.

**Expected behavior**
Sitemap folder to be created

```
System.IO.DirectoryNotFoundException: Directory 'Sitemaps' does not exist.
   at Smartstore.IO.LocalDirectory.EnumerateDirectories(String pattern, Boolean deep) in F:\Source\Smartstore\src\Smartstore\IO\LocalFileSystem\LocalDirectory.cs:line 172
   at Smartstore.IFileSystemExtensions.EnumerateDirectories(IFileSystem fs, String subpath, String pattern, Boolean deep) in F:\Source\Smartstore\src\Smartstore\IO\Extensions\IFileSystemExtensions.Directory.cs:line 103
   at Smartstore.Core.Seo.XmlSitemapGenerator.InvalidateAll() in F:\Source\Smartstore\src\Smartstore.Core\Platform\Seo\Services\XmlSitemapGenerator.cs:line 702
   at Smartstore.Core.Seo.XmlSitemapGenerator.OnAfterSaveAsync(IHookedEntity entry, CancellationToken cancelToken) in F:\Source\Smartstore\src\Smartstore.Core\Platform\Seo\Services\XmlSitemapGenerator.cs:line 95
   at Smartstore.Data.Hooks.DefaultDbHookProcessor.SaveChangesInternal(HookStage stage, IHookedEntity[] entries, HookImportance minHookImportance, CancellationToken cancelToken) in F:\Source\Smartstore\src\Smartstore\Data\Hooks\DefaultDbHookProcessor.cs:line 89
```
**Desktop (please complete the following information):**
 - OS: linux

**Comment by mgesing** [comment]
This has been [fixed](https://github.com/smartstore/Smartstore/commit/6abd22a02083c233bc5c489680aff4e8c5da3a20#diff-2db30b381c07a43a00239a0efb24a4c53992d919f10e6b53ea506972b9a4fba9R704) in the meantime.

**Comment by Algorithman** [comment]
Thx
