### ISSUE TITLE
Unable to cast object of type 'System.Int64' to type 'System.Nullable`1[System.Int32]'. 

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#679]
Hi,

http://localhost/admin/setting/order/

Controller: Error, Action: Error, Status: 500 (InternalServerError)
Unable to cast object of type 'System.Int64' to type 'System.Nullable`1[System.Int32]'.

```
System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Nullable`1[System.Int32]'.
   at Smartstore.DatabaseFacadeExtensions.ExecuteScalarRaw[T](DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters) in C:\Users\FB\source\repos\Smartstore\src\Smartstore\Data\Extensions\DatabaseFacadeExtensions.cs:line 100
   at Smartstore.DatabaseFacadeExtensions.ExecuteScalarRaw[T](DatabaseFacade databaseFacade, String sql, Object[] parameters) in C:\Users\FB\source\repos\Smartstore\src\Smartstore\Data\Extensions\DatabaseFacadeExtensions.cs:line 83
   at Smartstore.Data.Sqlite.SqliteDataProvider.GetTableIncrementCore(String tableName, Boolean async) in C:\Users\FB\source\repos\Smartstore\src\Smartstore.Data\Smartstore.Data.Sqlite\SqliteDataProvider.cs:line 157
   at Smartstore.Data.Providers.DataProvider.GetTableIdent[T]() in C:\Users\FB\source\repos\Smartstore\src\Smartstore\Data\Providers\DataProvider.cs:line 697
   at Smartstore.Admin.Controllers.SettingController.Order(Int32 storeScope, OrderSettings settings) in C:\Users\FB\source\repos\Smartstore\src\Smartstore.Web\Areas\Admin\Controllers\SettingController.cs:line 1294
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Smartstore.Core.Bootstrapping.CheckoutBootstrappingExtensions.<>c.<<UseCheckoutState>b__0_0>d.MoveNext() in C:\Users\FB\source\repos\Smartstore\src\Smartstore.Core\Checkout\Bootstrapping\CheckoutBootstrappingExtensions.cs:line 31
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Smartstore.Web.Api.Startup.<>c.<<BuildPipeline>b__3_6>d.MoveNext()
--- End of stack trace from previous location ---
   at Smartstore.ExceptionExtensions.ReThrow(Exception exception) in C:\Users\FB\source\repos\Smartstore\src\Smartstore\Extensions\ExceptionExtensions.cs:line 15
   at Smartstore.Web.Api.Startup.ProcessException(HttpContext context, Exception ex)
   at Smartstore.Web.Api.Startup.<>c.<<BuildPipeline>b__3_6>d.MoveNext()
--- End of stack trace from previous location ---
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 114
   at Smartstore.Core.Localization.RequestCultureMiddleware.Invoke(HttpContext context, IWorkContext workContext) in C:\Users\FB\source\repos\Smartstore\src\Smartstore.Core\Platform\Localization\Services\RequestCultureMiddleware.cs:line 71
   at Smartstore.Core.Logging.RequestLoggingMiddleware.InvokeAsync(HttpContext httpContext, IWebHelper webHelper, IWorkContext workContext) in C:\Users\FB\source\repos\Smartstore\src\Smartstore.Core\Platform\Logging\Serilog\RequestLoggingMiddleware.cs:line 78
   at Smartstore.Core.Bootstrapping.CommonBuilderExtensions.<>c.<<UseWorkContext>b__1_0>d.MoveNext() in C:\Users\FB\source\repos\Smartstore\src\Smartstore.Core\Platform\Common\Bootstrapping\CommonBuilderExtensions.cs:line 36
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Smartstore.Core.Bootstrapping.LocalizationBuilderExtensions.OnAfterRouting(HttpContext context, Func`1 next) in C:\Users\FB\source\repos\Smartstore\src\Smartstore.Core\Platform\Localization\Bootstrapping\LocalizationBuilderExtensions.cs:line 118
   at Smartstore.Core.Bootstrapping.LocalizationBuilderExtensions.OnBeforeRouting(HttpContext context, Func`1 next) in C:\Users\FB\source\repos\Smartstore\src\Smartstore.Core\Platform\Localization\Bootstrapping\LocalizationBuilderExtensions.cs:line 82
   at Microsoft.AspNetCore.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.OData.Query.ODataQueryRequestMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Smartstore.Core.Bootstrapping.CommonBuilderExtensions.<>c.<<UsePoweredBy>b__2_0>d.MoveNext() in C:\Users\FB\source\repos\Smartstore\src\Smartstore.Core\Platform\Common\Bootstrapping\CommonBuilderExtensions.cs:line 49
--- End of stack trace from previous location ---
   at Smartstore.Web.Bundling.BundleMiddleware.InvokeAsync(HttpContext httpContext) in C:\Users\FB\source\repos\Smartstore\src\Smartstore.Web.Common\Bundling\BundleMiddleware.cs:line 98
   at Smartstore.Engine.Initialization.ApplicationInitializerMiddleware.Invoke(HttpContext context) in C:\Users\FB\source\repos\Smartstore\src\Smartstore\Engine\Initialization\ApplicationInitializerMiddleware.cs:line 77
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Comment by suatsuphi** [comment]
```
An unhandled exception occurred while processing the request.
InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Nullable`1[System.Int32]'.
Smartstore.DatabaseFacadeExtensions.ExecuteScalarRaw<T>(DatabaseFacade databaseFacade, string sql, IEnumerable<object> parameters) in DatabaseFacadeExtensions.cs, line 100

Stack Query Cookies Headers Routing
InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Nullable`1[System.Int32]'.
Smartstore.DatabaseFacadeExtensions.ExecuteScalarRaw<T>(DatabaseFacade databaseFacade, string sql, IEnumerable<object> parameters) in DatabaseFacadeExtensions.cs
-
            using (concurrencyDetector.EnterCriticalSection())
            {
                var rawSqlCommand = facadeDependencies.RawSqlCommandBuilder
                    .Build(sql, parameters);
                return (T)rawSqlCommand
                    .RelationalCommand
                    .ExecuteScalar(
                        new RelationalCommandParameterObject(
                            facadeDependencies.RelationalConnection,
                            rawSqlCommand.ParameterValues,
                            null,
Smartstore.DatabaseFacadeExtensions.ExecuteScalarRaw<T>(DatabaseFacade databaseFacade, string sql, object[] parameters) in DatabaseFacadeExtensions.cs
-
            => ExecuteScalarRaw<T>(databaseFacade, sql.Format, sql.GetArguments());
        public static Task<T> ExecuteScalarInterpolatedAsync<T>(this DatabaseFacade databaseFacade, FormattableString sql, CancellationToken cancelToken = default)
            => ExecuteScalarRawAsync<T>(databaseFacade, sql.Format, sql.GetArguments(), cancelToken);
        public static T ExecuteScalarRaw<T>(this DatabaseFacade databaseFacade, string sql, params object[] parameters)
            => ExecuteScalarRaw<T>(databaseFacade, sql, parameters.AsEnumerable());
        public static T ExecuteScalarRaw<T>(this DatabaseFacade databaseFacade, string sql, IEnumerable<object> parameters)
        {
            Guard.NotNull(databaseFacade, nameof(databaseFacade));
            Guard.NotEmpty(sql, nameof(sql));
            Guard.NotNull(parameters, nameof(parameters));
Smartstore.Data.Sqlite.SqliteDataProvider.GetTableIncrementCore(string tableName, bool async) in SqliteDataProvider.cs
-
        }
        protected override Task<int?> GetTableIncrementCore(string tableName, bool async)
        {
            var sql = $"SELECT seq FROM sqlite_sequence WHERE name = \"{tableName}\"";
            return async
               ? Database.ExecuteScalarRawAsync<int?>(sql)
               : Task.FromResult(Database.ExecuteScalarRaw<int?>(sql));
        }
        protected override Task SetTableIncrementCore(string tableName, int ident, bool async)
        {
Smartstore.Data.Providers.DataProvider.GetTableIdent<T>() in DataProvider.cs
-
        /// Gets the current ident value
        /// </summary>
        /// <typeparam name="T">Entity</typeparam>
        /// <returns>Ident value or <c>null</c> if value cannot be resolved.</returns>
        public int? GetTableIdent<T>() where T : BaseEntity
        {
            return GetTableIncrementCore(Context.Model.FindEntityType(typeof(T)).GetTableName(), false).Await();
        }
        /// <summary>
        /// Gets the current ident value
        /// </summary>
        /// <typeparam name="T">Entity</typeparam>
Smartstore.Admin.Controllers.SettingController.Order(int storeScope, OrderSettings settings) in SettingController.cs
-
            AddLocales(model.Locales, (locale, languageId) =>
            {
                locale.ReturnRequestActions = settings.GetLocalizedSetting(x => x.ReturnRequestActions, languageId, storeScope, false, false);
                locale.ReturnRequestReasons = settings.GetLocalizedSetting(x => x.ReturnRequestReasons, languageId, storeScope, false, false);
            });
            model.OrderIdent = _db.DataProvider.GetTableIdent<Order>();
            return View(model);
        }
        [Permission(Permissions.Configuration.Setting.Update)]
        [HttpPost, SaveSetting]
```
